# Generated by Django 4.0.3 on 2022-04-09 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('registration_fee', models.IntegerField()),
                ('venue', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField()),
                ('no_of_attendees', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CoreBody',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('post', models.CharField(max_length=100)),
                ('duties', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duties', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InternationalChapter',
            fields=[
                ('yp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('region_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('issue', models.DateTimeField()),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('report_id', models.IntegerField(primary_key=True, serialize=False)),
                ('no_of_attendees', models.IntegerField()),
                ('proceedings', models.CharField(max_length=100)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cep.activities')),
            ],
        ),
        migrations.CreateModel(
            name='Views',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('international_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cep.corebody')),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cep.reports')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100, null=True)),
                ('domain', models.IntegerField()),
                ('no_of_members', models.IntegerField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cep.activities')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cep.generalmember')),
            ],
        ),
        migrations.CreateModel(
            name='Supervises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('international_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cep.corebody')),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cep.activities')),
            ],
        ),
        migrations.CreateModel(
            name='RequestView',
            fields=[
                ('request_date', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('issue_date', models.DateTimeField()),
                ('return_date', models.DateTimeField()),
                ('int_mem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cep.members')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cep.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='PartOf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cep.members')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cep.team')),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=100, null=True)),
                ('phonenumber', models.CharField(max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='members',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cep.myuser'),
        ),
        migrations.CreateModel(
            name='Manages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_mem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cep.corebody')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cep.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cep.myuser')),
            ],
        ),
        migrations.AddField(
            model_name='generalmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cep.members'),
        ),
        migrations.CreateModel(
            name='ExecutiveMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cep.members')),
            ],
        ),
        migrations.AddField(
            model_name='corebody',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cep.members'),
        ),
        migrations.AddField(
            model_name='corebody',
            name='ypid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cep.internationalchapter'),
        ),
        migrations.AddField(
            model_name='activities',
            name='member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cep.executivemembers'),
        ),
    ]
