# Generated by Django 4.0.3 on 2022-04-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cep', '0003_alter_myuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='event_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='corebody',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='internationalchapter',
            name='yp_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='item_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reports',
            name='report_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
