# Generated by Django 4.0.3 on 2022-04-13 16:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cep', '0006_alter_inventory_issue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestview',
            name='request_date',
        ),
        migrations.AddField(
            model_name='requestview',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requestview',
            name='issue_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
