# Generated by Django 4.0.3 on 2022-04-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cep', '0007_remove_requestview_request_date_requestview_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corebody',
            name='image_field',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
