# Generated by Django 4.0.3 on 2022-04-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cep', '0008_corebody_image_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corebody',
            name='image_field',
            field=models.ImageField(null=True, upload_to='core_body/'),
        ),
    ]
