# Generated by Django 4.0.3 on 2022-04-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cep', '0010_alter_corebody_image_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corebody',
            name='image_field',
            field=models.ImageField(default='core_body/avatar.jpg', upload_to='core_body/'),
        ),
    ]
