# Generated by Django 4.0.3 on 2022-04-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cep', '0011_alter_corebody_image_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corebody',
            name='image_field',
            field=models.ImageField(default='avatar.jpg', upload_to='core_body/'),
        ),
    ]
