# Generated by Django 4.0.3 on 2022-04-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cep', '0012_alter_corebody_image_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='executivemembers',
            name='image_field',
            field=models.ImageField(null=True, upload_to='executive_members/'),
        ),
        migrations.AlterField(
            model_name='corebody',
            name='image_field',
            field=models.ImageField(upload_to='core_body/'),
        ),
    ]
