# Generated by Django 4.0.3 on 2022-04-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cep', '0013_executivemembers_image_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='details',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
