# Generated by Django 4.0.3 on 2022-04-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cep', '0014_activities_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='image_field',
            field=models.ImageField(null=True, upload_to='activities/'),
        ),
    ]
