# Generated by Django 4.0.3 on 2022-04-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cep', '0015_activities_image_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
