# Generated by Django 4.0.3 on 2022-04-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cep', '0016_activities_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
